version: '3.8'

services:
  web:
    build: .
    command: sh -c "python manage.py migrate && gunicorn your_project.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis

  celery:
    build: .
    command: celery -A your_project worker --loglevel=info
    depends_on:
      - redis

  redis:
    image: redis:latest
