name: Django CI/CD with Docker, Celery, and Redis

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Build and start services
      run: docker-compose up -d --build

    - name: Wait for services to be ready
      run: sleep 20

    - name: Run tests
      run: docker-compose exec -T web python manage.py test
